### ISSUE TITLE
issue in App.jsx

### ISSUE THREAD

**Issue by enggsatyamraj** [Vimal-Mudalagi/reactRouterProject#1]
There is an issue in App.jsx.
This is the image for that.
<img width="382" alt="Screenshot 2024-03-01 at 12 05 24 AM" src="https://github.com/Vimal-Mudalagi/reactRouterProject/assets/118035430/e9985cb8-6528-46b7-9b25-abef7d563653">

**Comment by Vimal-Mudalagi** [comment]
Fixed it!
